# https://www.youtube.com/watch?v=H3iO8sbvUQg

name: Release

on:
  push:
    branches:
      - main
      - next

permissions:
  id-token: write # Required for OIDC
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout your repository code

        # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0 # Optional: specify a pnpm version, e.g., '8', 'latest', or a specific version like '8.6.0'

      # Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your preferred Node.js version
          cache: "pnpm" # Enable pnpm caching for faster dependency installation
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Audit signatures
        run: pnpm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release

      # - name: Publish
      #   run: pnpm publish
